language: go

sudo: required

go:
  - 1.6

services:
  - docker

install:
  - go env

script:
  - ./.travis/script.sh isolate isolate/docker isolate/process

after_success:
  - bash <(curl -s https://codecov.io/bash)
